version: '3.9'


networks:
  mysql-network:

services:
  pythonapp:
    build: ./python/
    command: sh -c "sleep 20s ; python3 ./op_db_check.py"
    depends_on:
      - mysql
    networks:
      - mysql-network    

  mysql:
    # image: mysql
    #container_name: mysql_db
    build: ./mysql/
    restart: always
    environment:
      MYSQL_DATABASE: 'op_db'
      #MYSQL_USER: 'JPQM'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - 3306:3306
    networks:
    - mysql-network


